disabled = false
languageCode = "zh-tw"
languageName = "Traditional Chinese"
weight = 1
title = "Rain Yu"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
   # logo = "frogsmile.png"
   #description = "My awesome website"
   copyright = "2025 RainYu"

 [params.author]
   name = "Rain Yu"
   email = "cbes.101065@gmail.com"
   image = "frogsmile.png"
   imageQuality = 96

   headline = "一隻可愛的青蛙"
   bio = "喜歡音樂、遊戲、打羽球的資工系學生"
   links = [
     { github = "https://github.com/RainYu0510/rainyu0510.github.io" },
     { instagram = "https://www.instagram.com/rainyu_05_10/" },
     { linkedin = "https://www.linkedin.com/in/%E9%AC%86-%E8%82%89-455105324/" },
   ]
